# Description: This file contains the categories mapping for the dataset.
# The categories mapping is used to map the categories in the dataset to a more general category.
# This was generated offline from a discussion around the dataset and the categories present in it.
updated_categories_mapping = {
    "beef": "beef",
    "chicken": "chicken",
    "bread": "bread",
    "lettuce": "lettuce",
    "cheese": "cheese",
    "pork": "pork",
    "spinach": "spinach",
    "egg": "egg",
    "salad dressing": "salad dressing",
    "yogurt": "yogurt",
    "rice": "rice",
    "turkey": "turkey",
    "mushrooms": "mushrooms",
    "peppers": "peppers",
    "orange juice": "juice",
    "milk": "milk",
    "carrots": "carrots",
    "kale": "kale",
    "onions": "onions",
    "corn": "corn",
    "tomatoes": "tomatoes",
    "cereals": "cereals",
    "peas": "peas",
    "muffins": "muffins",
    "cucumber": "cucumber",
    "pineapple": "pineapple",
    "peaches": "peaches",
    "broccoli": "broccoli",
    "cherries": "cherries",
    "waffles": "waffles",
    "coffee": "coffee",
    "pizza": "pizza",
    "blueberries": "blueberries",
    "fish": "fish",
    "strawberries": "strawberries",
    "apples": "apples",
    "cauliflower": "cauliflower",
    "pickles": "pickles",
    "radishes": "radishes",
    "macaroni": "pasta",
    "raspberries": "raspberries",
    "pastries": "pastries",
    "tangerines": "tangerines",
    "celery": "celery",
    "peanut butter": "peanut butter",
    "ice cream": "ice cream",
    "bananas": "bananas",
    "quinoa": "quinoa",
    "chowder": "chowder",
    "kiwifruit": "kiwifruit",
    "popcorn": "popcorn",
    "shrimp": "shrimp",
    "croissants": "croissants",
    "mangos": "mangos",
    "watermelon": "watermelon",
    "potatoes": "potatoes",
    "burrito": "burrito",
    "garlic bread": "garlic bread",
    "grits": "grits",
    "lasagna": "lasagna",
    "sandwich": "sandwich",
    "cake": "cake",
    "ravioli": "ravioli",
    "salmon": "fish",
    "hummus": "hummus",
    "asparagus": "asparagus",
    "baklava": "baklava",
    "beef tartare": "beef tartare",
    "beet salad": "salad",
    "beignets": "beignets",
    "bibimbap": "bibimbap",
    "bread pudding": "bread pudding",
    "bruschetta": "bruschetta",
    "calamari": "calamari",
    "caprese salad": "caprese salad",
    "carrot cake": "carrot cake",
    "ceviche": "ceviche",
    "cheese plate": "cheese",
    "cheese sandwich": "sandwich",
    "cheesecake": "cheesecake",
    "chips": "chips",
    "chips and salsa": "chips",
    "chocolate cake": "chocolate cake",
    "chocolate mousse": "chocolate mousse",
    "churros": "churros",
    "club sandwich": "sandwich",
    "crab cakes": "crab cakes",
    "creme brulee": "creme brulee",
    "croque madame": "croque madame",
    "cup cakes": "cup cakes",
    "deviled egg": "deviled egg",
    "donuts": "donuts",
    "edamame": "edamame",
    "egg benedict": "egg benedict",
    "escargots": "escargots",
    "falafel": "falafel",
    "foie gras": "foie gras",
    "french onion soup": "french onion soup",
    "gnocchi": "gnocchi",
    "greek salad": "salad",
    "gyoza": "gyoza",
    "hot and sour soup": "hot and sour soup",
    "huevos rancheros": "huevos rancheros",
    "jelly": "jelly",
    "lobster bisque": "lobster bisque",
    "lobster sandwich": "sandwich",
    "macarons": "macarons",
    "miso soup": "miso soup",
    "mussels": "mussels",
    "oyster": "oyster",
    "pad thai": "pad thai",
    "paella": "paella",
    "panna cotta": "panna cotta",
    "peking duck": "peking duck",
    "pho": "pho",
    "pork sandwich": "sandwich",
    "poutine": "poutine",
    "ramen": "ramen",
    "risotto": "risotto",
    "samosa": "samosa",
    "sashimi": "sashimi",
    "scallops": "scallops",
    "seaweed salad": "salad",
    "spaghetti bolognese": "pasta",
    "spaghetti carbonara": "pasta",
    "strawberry shortcake": "strawberry shortcake",
    "sushi": "sushi",
    "takoyaki": "takoyaki",
    "triamisu": "triamisu",
    "tuna tartare": "beef tartare",
    "bologna": "bologna",
    "potato salad": "salad",
    "dumplings": "gyoza",
    "hotdog": "hotdog",
    "onion rings": "onion rings",
    "avocados": "avocados",
    "fried rice": "fried rice",
    "arugula": "arugula",
    "bacon": "bacon",
    "cookie": "cookie",
    "oatmeal": "oatmeal",
    "tacos": "tacos",
    "apple pie": "apple pie",
    "guacamole": "guacamole",
    "fruit juice": "juice",
    "potato chips": "chips",
    "spaghetti": "pasta",
    "ham": "ham",
    "nachos": "nachos",
    "melons": "honeydew",
    "honeydrew melons": "honeydew",
    "salami": "salami",
    "tilapia": "fish",
    "tea": "tea",
    "pineapple juice": "juice",
    "pears": "pears",
    "steak": "steak",
    "cookies": "cookies",
    "apricots": "apricots",
    "french fries": "french fries",
    "lemonade": "lemonade",
    "sauce": "sauce",
    "water": "water",
    "cranberry juice": "juice",
    "biscuits": "biscuits",
    "cheese quesadilla": "cheese quesadilla",
    "caesar salad": "salad",
    "egg rolls": "egg rolls",
    "fruit punch": "fruit punch",
    "grape juice": "juice",
    "nuts": "nuts",
    "chicken quesadilla": "chicken quesadilla",
    "plums": "plums",
    "french dressing": "salad dressing",
    "almonds": "almonds",
    "apple juice": "juice",
    "hash brown": "hashbrowns",
    "hash browns": "hashbrowns",
    "smoothie": "smoothie",
    "pasta": "pasta",
    "russian dressing": "salad dressing",
    "blackberries": "blackberries",
    "cheeseburger": "cheeseburger",
}


def get_categories():
    # Return the unique categories that have been mapped
    return sorted(list(set(updated_categories_mapping.values())))


def get_category_count():
    return len(get_categories())
